---
dotfiles_repo: 'https://github.com/adalimayeu/dotfiles.git'
dotfiles_repo_version: master
dotfiles_files:
  - .oh-my-zsh/themes/oxide.zsh-theme
  - .aliases
  - .dircolors
  - .exports
  - .functions
  - .fzf.zsh
  - .ripgreprc
  - .zshrc
  # - .osx
  # - .gitconfig
  - .gitignore
